// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/turtacn/cbc/internal/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// AuthAppService is an autogenerated mock type for the AuthAppService type
type AuthAppService struct {
	mock.Mock
}

// IssueToken provides a mock function with given fields: ctx, req
func (_m *AuthAppService) IssueToken(ctx context.Context, req *dto.IssueTokenRequest) (*dto.TokenResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *dto.TokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, *dto.IssueTokenRequest) *dto.TokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.IssueTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: ctx, req
func (_m *AuthAppService) RefreshToken(ctx context.Context, req *dto.RefreshTokenRequest) (*dto.TokenResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *dto.TokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RefreshTokenRequest) *dto.TokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.RefreshTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeToken provides a mock function with given fields: ctx, req
func (_m *AuthAppService) RevokeToken(ctx context.Context, req *dto.RevokeTokenRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RevokeTokenRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IntrospectToken provides a mock function with given fields: ctx, token
func (_m *AuthAppService) IntrospectToken(ctx context.Context, token string) (*dto.TokenIntrospectionResponse, error) {
	ret := _m.Called(ctx, token)

	var r0 *dto.TokenIntrospectionResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.TokenIntrospectionResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenIntrospectionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterDevice provides a mock function with given fields: ctx, req
func (_m *AuthAppService) RegisterDevice(ctx context.Context, req *dto.RegisterDeviceRequest) (*dto.TokenResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *dto.TokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterDeviceRequest) *dto.TokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.RegisterDeviceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PollDeviceToken provides a mock function with given fields: ctx, deviceCode, clientID
func (_m *AuthAppService) PollDeviceToken(ctx context.Context, deviceCode string, clientID string) (*dto.TokenResponse, error) {
	ret := _m.Called(ctx, deviceCode, clientID)

	var r0 *dto.TokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.TokenResponse); ok {
		r0 = rf(ctx, deviceCode, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, deviceCode, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartDeviceFlow provides a mock function with given fields: ctx, clientID, scope
func (_m *AuthAppService) StartDeviceFlow(ctx context.Context, clientID string, scope string) (*dto.DeviceAuthResponse, error) {
	ret := _m.Called(ctx, clientID, scope)

	var r0 *dto.DeviceAuthResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.DeviceAuthResponse); ok {
		r0 = rf(ctx, clientID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeviceAuthResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clientID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyDeviceFlow provides a mock function with given fields: ctx, userCode, action, tenantID, subject
func (_m *AuthAppService) VerifyDeviceFlow(ctx context.Context, userCode string, action string, tenantID string, subject string) error {
	ret := _m.Called(ctx, userCode, action, tenantID, subject)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, userCode, action, tenantID, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
