// Code generated by Jules AI Test Generator. DO NOT EDIT.
package mocks

import (
	"context"
	"crypto/rsa"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/redis/go-redis/v9"
	"github.com/stretchr/testify/mock"
	"github.com/turtacn/cbc/internal/application/dto"
	"github.com/turtacn/cbc/internal/domain/service"
	"github.com/turtacn/cbc/pkg/constants"
)

// MockAuthAppService is a mock of AuthAppService
type MockAuthAppService struct {
	mock.Mock
}

func (m *MockAuthAppService) IssueToken(ctx context.Context, req *dto.TokenIssueRequest) (*dto.TokenResponse, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TokenResponse), args.Error(1)
}

func (m *MockAuthAppService) RefreshToken(ctx context.Context, req *dto.TokenRefreshRequest) (*dto.TokenResponse, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TokenResponse), args.Error(1)
}

func (m *MockAuthAppService) RevokeToken(ctx context.Context, req *dto.TokenRevokeRequest) error {
	args := m.Called(ctx, req)
	return args.Error(0)
}

func (m *MockAuthAppService) IntrospectToken(ctx context.Context, token string) (*dto.TokenIntrospectResponse, error) {
	args := m.Called(ctx, token)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TokenIntrospectResponse), args.Error(1)
}

func (m *MockAuthAppService) RegisterDevice(ctx context.Context, req *dto.DeviceRegisterRequest) (*dto.TokenResponse, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TokenResponse), args.Error(1)
}

// MockDeviceAppService is a mock of DeviceAppService
type MockDeviceAppService struct {
	mock.Mock
}

func (m *MockDeviceAppService) RegisterDevice(ctx context.Context, req *dto.DeviceRegisterRequest) (*dto.DeviceResponse, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.DeviceResponse), args.Error(1)
}

func (m *MockDeviceAppService) GetDeviceInfo(ctx context.Context, agentID string) (*dto.DeviceResponse, error) {
	args := m.Called(ctx, agentID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.DeviceResponse), args.Error(1)
}

func (m *MockDeviceAppService) UpdateDeviceInfo(ctx context.Context, agentID string, req *dto.DeviceUpdateRequest) (*dto.DeviceResponse, error) {
	args := m.Called(ctx, agentID, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.DeviceResponse), args.Error(1)
}

func (m *MockDeviceAppService) UpdateDeviceTrustLevel(ctx context.Context, agentID string, trustLevel constants.TrustLevel) error {
	args := m.Called(ctx, agentID, trustLevel)
	return args.Error(0)
}

func (m *MockDeviceAppService) DeactivateDevice(ctx context.Context, agentID string, reason string) error {
	args := m.Called(ctx, agentID, reason)
	return args.Error(0)
}

func (m *MockDeviceAppService) ListDevicesByTenant(ctx context.Context, tenantID string, page, pageSize int) ([]*dto.DeviceResponse, int64, error) {
	args := m.Called(ctx, tenantID, page, pageSize)
	if args.Get(0) == nil {
		return nil, int64(args.Int(1)), args.Error(2)
	}
	return args.Get(0).([]*dto.DeviceResponse), int64(args.Int(1)), args.Error(2)
}

func (m *MockDeviceAppService) VerifyDeviceFingerprint(ctx context.Context, agentID, fingerprint string) (bool, error) {
	args := m.Called(ctx, agentID, fingerprint)
	return args.Bool(0), args.Error(1)
}

// MockCryptoService is a mock of CryptoService
type MockCryptoService struct {
	mock.Mock
}

func (m *MockCryptoService) EncryptSensitiveData(ctx context.Context, data []byte) ([]byte, error) {
	args := m.Called(ctx, data)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]byte), args.Error(1)
}

func (m *MockCryptoService) DecryptSensitiveData(ctx context.Context, data []byte) ([]byte, error) {
	args := m.Called(ctx, data)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]byte), args.Error(1)
}

func (m *MockCryptoService) GenerateJWT(ctx context.Context, tenantID string, claims jwt.Claims) (string, string, error) {
	args := m.Called(ctx, tenantID, claims)
	return args.String(0), args.String(1), args.Error(2)
}

func (m *MockCryptoService) VerifyJWT(ctx context.Context, tokenString string, tenantID string) (jwt.MapClaims, error) {
	args := m.Called(ctx, tokenString, tenantID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(jwt.MapClaims), args.Error(1)
}

func (m *MockCryptoService) GetPublicKey(ctx context.Context, tenantID, kid string) (*rsa.PublicKey, error) {
	args := m.Called(ctx, tenantID, kid)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*rsa.PublicKey), args.Error(1)
}

func (m *MockCryptoService) GetPrivateKey(ctx context.Context, tenantID string) (*rsa.PrivateKey, string, error) {
	args := m.Called(ctx, tenantID)
	if args.Get(0) == nil {
		return nil, "", args.Error(2)
	}
	return args.Get(0).(*rsa.PrivateKey), args.String(1), args.Error(2)
}

func (m *MockCryptoService) RotateKey(ctx context.Context, tenantID string) (string, error) {
	args := m.Called(ctx, tenantID)
	return args.String(0), args.Error(1)
}

// MockRedisConnectionManager is a mock of RedisConnectionManager
type MockRedisConnectionManager struct {
	mock.Mock
}

func (m *MockRedisConnectionManager) GetClient() redis.UniversalClient {
	args := m.Called()
	if args.Get(0) == nil {
		return nil
	}
	return args.Get(0).(redis.UniversalClient)
}

func (m *MockRedisConnectionManager) Close() error {
	args := m.Called()
	return args.Error(0)
}

func (m *MockRedisConnectionManager) Ping(ctx context.Context) error {
	args := m.Called(ctx)
	return args.Error(0)
}

func (m *MockRedisConnectionManager) HealthCheck(ctx context.Context) (map[string]interface{}, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(map[string]interface{}), args.Error(1)
}

// MockRateLimitService is a mock of RateLimitService
type MockRateLimitService struct {
	mock.Mock
}

func (m *MockRateLimitService) Allow(ctx context.Context, dimension service.RateLimitDimension, key string, identifier string) (bool, int, time.Time, error) {
	args := m.Called(ctx, dimension, key, identifier)
	return args.Bool(0), args.Int(1), args.Get(2).(time.Time), args.Error(3)
}

// MockHTTPMetrics is a mock of HTTPMetrics
type MockHTTPMetrics struct {
	mock.Mock
}

func (m *MockHTTPMetrics) RecordRequestStart(ctx context.Context, operation string) {
	m.Called(ctx, operation)
}

func (m *MockHTTPMetrics) RecordRequestDuration(ctx context.Context, operation string, code int, d time.Duration) {
	m.Called(ctx, operation, code, d)
}

func (m *MockHTTPMetrics) RecordRequestError(ctx context.Context, route string, status int) {
	m.Called(ctx, route, status)
}
