// Code generated by Jules AI Test Generator. DO NOT EDIT.
package redis

import (
	"context"

	"github.com/redis/go-redis/v9"
)

//go:generate mockery --name RedisConnectionManager --output ../../../domain/service/mocks --outpkg mocks
// RedisConnectionManager defines the interface for managing Redis connections.
// This allows for mocking in tests.
type RedisConnectionManager interface {
	GetClient() redis.UniversalClient
	Close() error
	Ping(ctx context.Context) error
	HealthCheck(ctx context.Context) (map[string]interface{}, error)
}
