// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/turtacn/cbc/internal/application/dto"
)

// AuthAppService is an autogenerated mock type for the AuthAppService type
type AuthAppService struct {
	mock.Mock
}

// IntrospectToken provides a mock function with given fields: ctx, token
func (_m *AuthAppService) IntrospectToken(ctx context.Context, token string) (*dto.TokenIntrospectResponse, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IntrospectToken")
	}

	var r0 *dto.TokenIntrospectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.TokenIntrospectResponse, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.TokenIntrospectResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenIntrospectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IssueToken provides a mock function with given fields: ctx, req
func (_m *AuthAppService) IssueToken(ctx context.Context, req *dto.TokenIssueRequest) (*dto.TokenResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 *dto.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.TokenIssueRequest) (*dto.TokenResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.TokenIssueRequest) *dto.TokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.TokenIssueRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: ctx, req
func (_m *AuthAppService) RefreshToken(ctx context.Context, req *dto.TokenRefreshRequest) (*dto.TokenResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dto.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.TokenRefreshRequest) (*dto.TokenResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.TokenRefreshRequest) *dto.TokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.TokenRefreshRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeToken provides a mock function with given fields: ctx, req
func (_m *AuthAppService) RevokeToken(ctx context.Context, req *dto.TokenRevokeRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.TokenRevokeRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthAppService creates a new instance of AuthAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthAppService {
	mock := &AuthAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
