// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/turtacn/cbc/internal/application/dto"
)

// MockDeviceAuthAppService is an autogenerated mock type for the DeviceAuthAppService type
type MockDeviceAuthAppService struct {
	mock.Mock
}

// PollDeviceToken provides a mock function with given fields: ctx, deviceCode, clientID
func (_m *MockDeviceAuthAppService) PollDeviceToken(ctx context.Context, deviceCode string, clientID string) (*dto.TokenResponse, error) {
	ret := _m.Called(ctx, deviceCode, clientID)

	if len(ret) == 0 {
		panic("no return value specified for PollDeviceToken")
	}

	var r0 *dto.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.TokenResponse, error)); ok {
		return rf(ctx, deviceCode, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.TokenResponse); ok {
		r0 = rf(ctx, deviceCode, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, deviceCode, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterDevice provides a mock function with given fields: ctx, req
func (_m *MockDeviceAuthAppService) RegisterDevice(ctx context.Context, req *dto.DeviceRegisterRequest) (*dto.TokenResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDevice")
	}

	var r0 *dto.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeviceRegisterRequest) (*dto.TokenResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeviceRegisterRequest) *dto.TokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.DeviceRegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartDeviceFlow provides a mock function with given fields: ctx, clientID, scope
func (_m *MockDeviceAuthAppService) StartDeviceFlow(ctx context.Context, clientID string, scope string) (*dto.DeviceAuthResponse, error) {
	ret := _m.Called(ctx, clientID, scope)

	if len(ret) == 0 {
		panic("no return value specified for StartDeviceFlow")
	}

	var r0 *dto.DeviceAuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.DeviceAuthResponse, error)); ok {
		return rf(ctx, clientID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.DeviceAuthResponse); ok {
		r0 = rf(ctx, clientID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeviceAuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clientID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyDeviceFlow provides a mock function with given fields: ctx, userCode, action, tenantID, subject
func (_m *MockDeviceAuthAppService) VerifyDeviceFlow(ctx context.Context, userCode string, action string, tenantID string, subject string) error {
	ret := _m.Called(ctx, userCode, action, tenantID, subject)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDeviceFlow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, userCode, action, tenantID, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDeviceAuthAppService creates a new instance of MockDeviceAuthAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceAuthAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceAuthAppService {
	mock := &MockDeviceAuthAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
