// Code generated by Jules AI Test Generator. DO NOT EDIT.
package consumers

import (
	"context"
	"testing"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/segmentio/kafka-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/turtacn/cbc/internal/domain/models"
	"github.com/turtacn/cbc/pkg/logger"
)

// MockKafkaReader is a mock for the kafka.Reader.
type MockKafkaReader struct {
	mock.Mock
}

func (m *MockKafkaReader) FetchMessage(ctx context.Context) (kafka.Message, error) {
	args := m.Called(ctx)
	return args.Get(0).(kafka.Message), args.Error(1)
}

func (m *MockKafkaReader) CommitMessages(ctx context.Context, msgs ...kafka.Message) error {
	args := m.Called(ctx, msgs)
	return args.Error(0)
}

func (m *MockKafkaReader) Close() error {
	args := m.Called()
	return args.Error(0)
}

// MockRedisClient is a mock for the redis.UniversalClient.
type MockRedisClient struct {
	mock.Mock
	redis.UniversalClient
}

func (m *MockRedisClient) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.StatusCmd {
	args := m.Called(ctx, key, value, expiration)
	return args.Get(0).(*redis.StatusCmd)
}

func TestRevocationConsumer_handleEvent(t *testing.T) {
	mockRedis := new(MockRedisClient)
	noopLogger := logger.NewNoopLogger()

	// The consumer's reader isn't used in handleEvent, so we can pass a dummy one.
	consumer := &RevocationConsumer{
		rdb:    mockRedis,
		logger: noopLogger,
	}

	ctx := context.Background()
	jti := "test-jti-123"
	tenantID := "tenant-abc"
	exp := time.Now().Add(1 * time.Hour)

	event := models.AuditEvent{
		Action:   "token_revoked_globally",
		TenantID: tenantID,
		Actor:    "system",
		Metadata: models.Metadata{
			"jti":        jti,
			"expires_at": exp.Format(time.RFC3339),
		},
	}

	expectedKey := "cbc:bl:" + tenantID + ":" + jti
	expectedTTL := time.Until(exp)

	// Set up the mock expectation for Redis
	statusCmd := redis.NewStatusCmd(ctx)
	statusCmd.SetVal("OK")
	mockRedis.On("Set", ctx, expectedKey, "1", mock.AnythingOfType("time.Duration")).Run(func(args mock.Arguments) {
		// Assert TTL is within a reasonable range of the expected TTL
		ttl := args.Get(3).(time.Duration)
		assert.InDelta(t, expectedTTL, ttl, float64(time.Second))
	}).Return(statusCmd).Once()

	err := consumer.handleEvent(ctx, event)
	assert.NoError(t, err)

	mockRedis.AssertExpectations(t)
}
