package models

import "time"

// TenantRiskProfile represents a dynamic risk assessment for a specific tenant.
// This profile is typically generated by an external machine learning or security analytics system.
// TenantRiskProfile 代表特定租户的动态风险评估。
// 此配置文件通常由外部机器学习或安全分析系统生成。
type TenantRiskProfile struct {
	// TenantID is the identifier of the tenant to whom this risk profile applies.
	// TenantID 是此风险配置文件适用的租户的标识符。
	TenantID string `json:"tenant_id" gorm:"primaryKey"`
	// AnomalyScore is a numerical value representing the deviation from normal behavior, where higher is riskier.
	// AnomalyScore 是一个数值，表示与正常行为的偏差，数值越高风险越大。
	AnomalyScore float64 `json:"anomaly_score"`
	// PredictedThreat is a categorical label for the most likely threat type (e.g., "credential_stuffing", "brute_force").
	// PredictedThreat 是最可能的威胁类型的分类标签（例如，“凭证填充”、“暴力破解”）。
	PredictedThreat string `json:"predicted_threat"`
	// LastUpdated is the timestamp when this risk profile was last calculated and updated.
	// LastUpdated 是上次计算和更新此风险配置文件的时间戳。
	LastUpdated time.Time `json:"last_updated"`
	// TrustedIPs is a list of IP addresses that are considered trusted for this tenant.
	TrustedIPs []string `json:"trusted_ips,omitempty" gorm:"type:json"`
	// BlockedIPs is a list of IP addresses that are explicitly blocked for this tenant.
	BlockedIPs []string `json:"blocked_ips,omitempty" gorm:"type:json"`
}

// TrustLevel is a categorical representation of device or tenant trust.
type TrustLevel string

const (
	// TrustLevelHigh indicates a high level of trust.
	TrustLevelHigh TrustLevel = "high"
	// TrustLevelMedium indicates a medium level of trust.
	TrustLevelMedium TrustLevel = "medium"
	// TrustLevelLow indicates a low level of trust.
	TrustLevelLow TrustLevel = "low"
)
