// Code generated by Jules AI Test Generator. DO NOT EDIT.
package policy_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/turtacn/cbc/internal/domain/models"
	"github.com/turtacn/cbc/internal/infrastructure/policy"
)

func Test_EvaluateTrustLevel_IP_Rules(t *testing.T) {
	engine, err := policy.NewStaticPolicyEngine("../../../../config/policies.yaml")
	assert.NoError(t, err)

	testCases := []struct {
		name           string
		riskProfile    *models.TenantRiskProfile
		clientIP       string
		expectedLevel  models.TrustLevel
	}{
		{
			name: "IP is in block list",
			riskProfile: &models.TenantRiskProfile{
				BlockedIPs: []string{"1.2.3.4", "5.6.7.8"},
			},
			clientIP:      "1.2.3.4",
			expectedLevel: models.TrustLevelLow,
		},
		{
			name: "IP is in trusted list",
			riskProfile: &models.TenantRiskProfile{
				TrustedIPs: []string{"8.8.8.8", "9.9.9.9"},
			},
			clientIP:      "8.8.8.8",
			expectedLevel: models.TrustLevelHigh,
		},
		{
			name: "IP is in both lists (block takes precedence)",
			riskProfile: &models.TenantRiskProfile{
				TrustedIPs: []string{"8.8.8.8", "9.9.9.9"},
				BlockedIPs: []string{"1.2.3.4", "8.8.8.8"},
			},
			clientIP:      "8.8.8.8",
			expectedLevel: models.TrustLevelLow,
		},
		{
			name: "IP not in any list - fallback to high anomaly score",
			riskProfile: &models.TenantRiskProfile{
				AnomalyScore: 0.8,
			},
			clientIP:      "10.10.10.10",
			expectedLevel: models.TrustLevelLow,
		},
		{
			name: "IP not in any list - fallback to medium anomaly score",
			riskProfile: &models.TenantRiskProfile{
				AnomalyScore: 0.6,
			},
			clientIP:      "10.10.10.10",
			expectedLevel: models.TrustLevelMedium,
		},
		{
			name: "IP not in any list - fallback to low anomaly score",
			riskProfile: &models.TenantRiskProfile{
				AnomalyScore: 0.2,
			},
			clientIP:      "10.10.10.10",
			expectedLevel: models.TrustLevelHigh,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			level := engine.EvaluateTrustLevel(context.Background(), tc.riskProfile, tc.clientIP)
			assert.Equal(t, tc.expectedLevel, level)
		})
	}
}
