// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/turtacn/cbc/internal/domain/models"
)

// DeviceRepository is an autogenerated mock type for the DeviceRepository type
type DeviceRepository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, agentID
func (_m *DeviceRepository) FindByID(ctx context.Context, agentID string) (*models.Device, error) {
	ret := _m.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Device, error)); ok {
		return rf(ctx, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Device); ok {
		r0 = rf(ctx, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTenantID provides a mock function with given fields: ctx, tenantID, page, pageSize
func (_m *DeviceRepository) FindByTenantID(ctx context.Context, tenantID string, page int, pageSize int) ([]*models.Device, int64, error) {
	ret := _m.Called(ctx, tenantID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindByTenantID")
	}

	var r0 []*models.Device
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*models.Device, int64, error)); ok {
		return rf(ctx, tenantID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*models.Device); ok {
		r0 = rf(ctx, tenantID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, tenantID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, tenantID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Save provides a mock function with given fields: ctx, device
func (_m *DeviceRepository) Save(ctx context.Context, device *models.Device) error {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Device) error); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, device
func (_m *DeviceRepository) Update(ctx context.Context, device *models.Device) error {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Device) error); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeviceRepository creates a new instance of DeviceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceRepository {
	mock := &DeviceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
