// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/turtacn/cbc/internal/domain/models"
)

// KeyRepository is an autogenerated mock type for the KeyRepository type
type KeyRepository struct {
	mock.Mock
}

// CreateKey provides a mock function with given fields: ctx, key
func (_m *KeyRepository) CreateKey(ctx context.Context, key *models.Key) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CreateKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Key) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveKeys provides a mock function with given fields: ctx, tenantID
func (_m *KeyRepository) GetActiveKeys(ctx context.Context, tenantID string) ([]*models.Key, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveKeys")
	}

	var r0 []*models.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.Key, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Key); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeprecatedKeys provides a mock function with given fields: ctx, tenantID
func (_m *KeyRepository) GetDeprecatedKeys(ctx context.Context, tenantID string) ([]*models.Key, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeprecatedKeys")
	}

	var r0 []*models.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.Key, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Key); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKeyByKID provides a mock function with given fields: ctx, tenantID, kid
func (_m *KeyRepository) GetKeyByKID(ctx context.Context, tenantID string, kid string) (*models.Key, error) {
	ret := _m.Called(ctx, tenantID, kid)

	if len(ret) == 0 {
		panic("no return value specified for GetKeyByKID")
	}

	var r0 *models.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Key, error)); ok {
		return rf(ctx, tenantID, kid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Key); ok {
		r0 = rf(ctx, tenantID, kid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, kid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKeyStatus provides a mock function with given fields: ctx, tenantID, kid, status
func (_m *KeyRepository) UpdateKeyStatus(ctx context.Context, tenantID string, kid string, status string) error {
	ret := _m.Called(ctx, tenantID, kid, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKeyStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tenantID, kid, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKeyRepository creates a new instance of KeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyRepository {
	mock := &KeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
