// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/turtacn/cbc/internal/domain/models"
)

// RiskRepository is an autogenerated mock type for the RiskRepository type
type RiskRepository struct {
	mock.Mock
}

// GetTenantRiskProfile provides a mock function with given fields: ctx, tenantID
func (_m *RiskRepository) GetTenantRiskProfile(ctx context.Context, tenantID string) (*models.TenantRiskProfile, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantRiskProfile")
	}

	var r0 *models.TenantRiskProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.TenantRiskProfile, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.TenantRiskProfile); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TenantRiskProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertTenantRiskProfile provides a mock function with given fields: ctx, profile
func (_m *RiskRepository) UpsertTenantRiskProfile(ctx context.Context, profile *models.TenantRiskProfile) error {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTenantRiskProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TenantRiskProfile) error); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRiskRepository creates a new instance of RiskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskRepository {
	mock := &RiskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
