// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	constants "github.com/turtacn/cbc/pkg/constants"

	mock "github.com/stretchr/testify/mock"

	models "github.com/turtacn/cbc/internal/domain/models"

	repository "github.com/turtacn/cbc/internal/domain/repository"

	time "time"
)

// TenantRepository is an autogenerated mock type for the TenantRepository type
type TenantRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, tenantID
func (_m *TenantRepository) Delete(ctx context.Context, tenantID string) error {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, tenantID
func (_m *TenantRepository) Exists(ctx context.Context, tenantID string) (bool, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindActiveAll provides a mock function with given fields: ctx
func (_m *TenantRepository) FindActiveAll(ctx context.Context) ([]*models.Tenant, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveAll")
	}

	var r0 []*models.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Tenant, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Tenant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, limit, offset
func (_m *TenantRepository) FindAll(ctx context.Context, limit int, offset int) ([]*models.Tenant, int64, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*models.Tenant
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Tenant, int64, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Tenant); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, tenantID
func (_m *TenantRepository) FindByID(ctx context.Context, tenantID string) (*models.Tenant, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Tenant, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Tenant); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *TenantRepository) FindByName(ctx context.Context, name string) (*models.Tenant, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Tenant, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Tenant); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllMetrics provides a mock function with given fields: ctx
func (_m *TenantRepository) GetAllMetrics(ctx context.Context) (*repository.SystemMetrics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMetrics")
	}

	var r0 *repository.SystemMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*repository.SystemMetrics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *repository.SystemMetrics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.SystemMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTenantMetrics provides a mock function with given fields: ctx, tenantID
func (_m *TenantRepository) GetTenantMetrics(ctx context.Context, tenantID string) (*repository.TenantMetrics, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantMetrics")
	}

	var r0 *repository.TenantMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*repository.TenantMetrics, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *repository.TenantMetrics); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.TenantMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementRequestCount provides a mock function with given fields: ctx, tenantID, count
func (_m *TenantRepository) IncrementRequestCount(ctx context.Context, tenantID string, count int64) error {
	ret := _m.Called(ctx, tenantID, count)

	if len(ret) == 0 {
		panic("no return value specified for IncrementRequestCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, tenantID, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, tenant
func (_m *TenantRepository) Save(ctx context.Context, tenant *models.Tenant) error {
	ret := _m.Called(ctx, tenant)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Tenant) error); ok {
		r0 = rf(ctx, tenant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, tenant
func (_m *TenantRepository) Update(ctx context.Context, tenant *models.Tenant) error {
	ret := _m.Called(ctx, tenant)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Tenant) error); ok {
		r0 = rf(ctx, tenant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateKeyRotationPolicy provides a mock function with given fields: ctx, tenantID, policy
func (_m *TenantRepository) UpdateKeyRotationPolicy(ctx context.Context, tenantID string, policy *models.KeyRotationPolicy) error {
	ret := _m.Called(ctx, tenantID, policy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKeyRotationPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.KeyRotationPolicy) error); ok {
		r0 = rf(ctx, tenantID, policy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastActivityAt provides a mock function with given fields: ctx, tenantID, lastActivityAt
func (_m *TenantRepository) UpdateLastActivityAt(ctx context.Context, tenantID string, lastActivityAt time.Time) error {
	ret := _m.Called(ctx, tenantID, lastActivityAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastActivityAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, tenantID, lastActivityAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRateLimitConfig provides a mock function with given fields: ctx, tenantID, config
func (_m *TenantRepository) UpdateRateLimitConfig(ctx context.Context, tenantID string, config *models.RateLimitConfig) error {
	ret := _m.Called(ctx, tenantID, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRateLimitConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.RateLimitConfig) error); ok {
		r0 = rf(ctx, tenantID, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, tenantID, status
func (_m *TenantRepository) UpdateStatus(ctx context.Context, tenantID string, status constants.TenantStatus) error {
	ret := _m.Called(ctx, tenantID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, constants.TenantStatus) error); ok {
		r0 = rf(ctx, tenantID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTokenTTLConfig provides a mock function with given fields: ctx, tenantID, config
func (_m *TenantRepository) UpdateTokenTTLConfig(ctx context.Context, tenantID string, config *models.TokenTTLConfig) error {
	ret := _m.Called(ctx, tenantID, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenTTLConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.TokenTTLConfig) error); ok {
		r0 = rf(ctx, tenantID, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTenantRepository creates a new instance of TenantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantRepository {
	mock := &TenantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
