apiVersion: v1
kind: ConfigMap
metadata:
  name: cbc-auth-config
  namespace: cbc-auth
data:
  redis-addresses: "redis-cluster.cbc-auth.svc.cluster.local:6379"
  vault-address: "https://vault.cbc-auth.svc.cluster.local:8200"
  log-level: "info"
  tracing-enabled: "true"
  jaeger-endpoint: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"
#Personal.AI order the ending