// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RiskUpdateService is an autogenerated mock type for the RiskUpdateService type
type RiskUpdateService struct {
	mock.Mock
}

// UpdateTenantRisk provides a mock function with given fields: ctx, tenantID, score, threat
func (_m *RiskUpdateService) UpdateTenantRisk(ctx context.Context, tenantID string, score float64, threat string) error {
	ret := _m.Called(ctx, tenantID, score, threat)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTenantRisk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, string) error); ok {
		r0 = rf(ctx, tenantID, score, threat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRiskUpdateService creates a new instance of RiskUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskUpdateService {
	mock := &RiskUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
