// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	rsa "crypto/rsa"
)

// CryptoService is an autogenerated mock type for the CryptoService type
type CryptoService struct {
	mock.Mock
}

// DecryptSensitiveData provides a mock function with given fields: ctx, data
func (_m *CryptoService) DecryptSensitiveData(ctx context.Context, data []byte) ([]byte, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for DecryptSensitiveData")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptSensitiveData provides a mock function with given fields: ctx, data
func (_m *CryptoService) EncryptSensitiveData(ctx context.Context, data []byte) ([]byte, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for EncryptSensitiveData")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateJWT provides a mock function with given fields: ctx, tenantID, claims
func (_m *CryptoService) GenerateJWT(ctx context.Context, tenantID string, claims jwt.Claims) (string, string, error) {
	ret := _m.Called(ctx, tenantID, claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, jwt.Claims) (string, string, error)); ok {
		return rf(ctx, tenantID, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, jwt.Claims) string); ok {
		r0 = rf(ctx, tenantID, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, jwt.Claims) string); ok {
		r1 = rf(ctx, tenantID, claims)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, jwt.Claims) error); ok {
		r2 = rf(ctx, tenantID, claims)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPrivateKey provides a mock function with given fields: ctx, tenantID
func (_m *CryptoService) GetPrivateKey(ctx context.Context, tenantID string) (*rsa.PrivateKey, string, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKey")
	}

	var r0 *rsa.PrivateKey
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*rsa.PrivateKey, string, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *rsa.PrivateKey); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PrivateKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, tenantID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPublicKey provides a mock function with given fields: ctx, tenantID, keyID
func (_m *CryptoService) GetPublicKey(ctx context.Context, tenantID string, keyID string) (*rsa.PublicKey, error) {
	ret := _m.Called(ctx, tenantID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 *rsa.PublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*rsa.PublicKey, error)); ok {
		return rf(ctx, tenantID, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *rsa.PublicKey); ok {
		r0 = rf(ctx, tenantID, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateKey provides a mock function with given fields: ctx, tenantID
func (_m *CryptoService) RotateKey(ctx context.Context, tenantID string) (string, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for RotateKey")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyJWT provides a mock function with given fields: ctx, tokenString, tenantID
func (_m *CryptoService) VerifyJWT(ctx context.Context, tokenString string, tenantID string) (jwt.MapClaims, error) {
	ret := _m.Called(ctx, tokenString, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyJWT")
	}

	var r0 jwt.MapClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (jwt.MapClaims, error)); ok {
		return rf(ctx, tokenString, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) jwt.MapClaims); ok {
		r0 = rf(ctx, tokenString, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tokenString, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCryptoService creates a new instance of CryptoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCryptoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CryptoService {
	mock := &CryptoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
