// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	constants "github.com/turtacn/cbc/pkg/constants"

	dto "github.com/turtacn/cbc/internal/application/dto"

	mock "github.com/stretchr/testify/mock"
)

// DeviceAppService is an autogenerated mock type for the DeviceAppService type
type DeviceAppService struct {
	mock.Mock
}

// DeactivateDevice provides a mock function with given fields: ctx, agentID, reason
func (_m *DeviceAppService) DeactivateDevice(ctx context.Context, agentID string, reason string) error {
	ret := _m.Called(ctx, agentID, reason)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, agentID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDeviceInfo provides a mock function with given fields: ctx, agentID
func (_m *DeviceAppService) GetDeviceInfo(ctx context.Context, agentID string) (*dto.DeviceResponse, error) {
	ret := _m.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceInfo")
	}

	var r0 *dto.DeviceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.DeviceResponse, error)); ok {
		return rf(ctx, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.DeviceResponse); ok {
		r0 = rf(ctx, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeviceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDevicesByTenant provides a mock function with given fields: ctx, tenantID, page, pageSize
func (_m *DeviceAppService) ListDevicesByTenant(ctx context.Context, tenantID string, page int, pageSize int) ([]*dto.DeviceResponse, int64, error) {
	ret := _m.Called(ctx, tenantID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListDevicesByTenant")
	}

	var r0 []*dto.DeviceResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*dto.DeviceResponse, int64, error)); ok {
		return rf(ctx, tenantID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*dto.DeviceResponse); ok {
		r0 = rf(ctx, tenantID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.DeviceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, tenantID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, tenantID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterDevice provides a mock function with given fields: ctx, req
func (_m *DeviceAppService) RegisterDevice(ctx context.Context, req *dto.DeviceRegisterRequest) (*dto.DeviceResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDevice")
	}

	var r0 *dto.DeviceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeviceRegisterRequest) (*dto.DeviceResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeviceRegisterRequest) *dto.DeviceResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeviceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.DeviceRegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDeviceInfo provides a mock function with given fields: ctx, agentID, req
func (_m *DeviceAppService) UpdateDeviceInfo(ctx context.Context, agentID string, req *dto.DeviceUpdateRequest) (*dto.DeviceResponse, error) {
	ret := _m.Called(ctx, agentID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeviceInfo")
	}

	var r0 *dto.DeviceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.DeviceUpdateRequest) (*dto.DeviceResponse, error)); ok {
		return rf(ctx, agentID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.DeviceUpdateRequest) *dto.DeviceResponse); ok {
		r0 = rf(ctx, agentID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeviceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.DeviceUpdateRequest) error); ok {
		r1 = rf(ctx, agentID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDeviceTrustLevel provides a mock function with given fields: ctx, agentID, trustLevel
func (_m *DeviceAppService) UpdateDeviceTrustLevel(ctx context.Context, agentID string, trustLevel constants.TrustLevel) error {
	ret := _m.Called(ctx, agentID, trustLevel)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeviceTrustLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, constants.TrustLevel) error); ok {
		r0 = rf(ctx, agentID, trustLevel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyDeviceFingerprint provides a mock function with given fields: ctx, agentID, fingerprint
func (_m *DeviceAppService) VerifyDeviceFingerprint(ctx context.Context, agentID string, fingerprint string) (bool, error) {
	ret := _m.Called(ctx, agentID, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDeviceFingerprint")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, agentID, fingerprint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, agentID, fingerprint)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, agentID, fingerprint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDeviceAppService creates a new instance of DeviceAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceAppService {
	mock := &DeviceAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
