// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/turtacn/cbc/internal/domain/models"
)

// DeviceAuthStore is an autogenerated mock type for the DeviceAuthStore type
type DeviceAuthStore struct {
	mock.Mock
}

// ApproveSession provides a mock function with given fields: ctx, userCode, tenantID, subject
func (_m *DeviceAuthStore) ApproveSession(ctx context.Context, userCode string, tenantID string, subject string) error {
	ret := _m.Called(ctx, userCode, tenantID, subject)

	if len(ret) == 0 {
		panic("no return value specified for ApproveSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userCode, tenantID, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSession provides a mock function with given fields: ctx, session
func (_m *DeviceAuthStore) CreateSession(ctx context.Context, session *models.DeviceAuthSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.DeviceAuthSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DenySession provides a mock function with given fields: ctx, userCode
func (_m *DeviceAuthStore) DenySession(ctx context.Context, userCode string) error {
	ret := _m.Called(ctx, userCode)

	if len(ret) == 0 {
		panic("no return value specified for DenySession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSessionByDeviceCode provides a mock function with given fields: ctx, deviceCode
func (_m *DeviceAuthStore) GetSessionByDeviceCode(ctx context.Context, deviceCode string) (*models.DeviceAuthSession, error) {
	ret := _m.Called(ctx, deviceCode)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByDeviceCode")
	}

	var r0 *models.DeviceAuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.DeviceAuthSession, error)); ok {
		return rf(ctx, deviceCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.DeviceAuthSession); ok {
		r0 = rf(ctx, deviceCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeviceAuthSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deviceCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSessionByUserCode provides a mock function with given fields: ctx, userCode
func (_m *DeviceAuthStore) GetSessionByUserCode(ctx context.Context, userCode string) (*models.DeviceAuthSession, error) {
	ret := _m.Called(ctx, userCode)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByUserCode")
	}

	var r0 *models.DeviceAuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.DeviceAuthSession, error)); ok {
		return rf(ctx, userCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.DeviceAuthSession); ok {
		r0 = rf(ctx, userCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeviceAuthSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TouchPoll provides a mock function with given fields: ctx, deviceCode
func (_m *DeviceAuthStore) TouchPoll(ctx context.Context, deviceCode string) error {
	ret := _m.Called(ctx, deviceCode)

	if len(ret) == 0 {
		panic("no return value specified for TouchPoll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, deviceCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeviceAuthStore creates a new instance of DeviceAuthStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceAuthStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceAuthStore {
	mock := &DeviceAuthStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
