// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HTTPMetrics is an autogenerated mock type for the HTTPMetrics type
type HTTPMetrics struct {
	mock.Mock
}

// RecordRequestDuration provides a mock function with given fields: ctx, route, status, d
func (_m *HTTPMetrics) RecordRequestDuration(ctx context.Context, route string, status int, d time.Duration) {
	_m.Called(ctx, route, status, d)
}

// RecordRequestError provides a mock function with given fields: ctx, route, status
func (_m *HTTPMetrics) RecordRequestError(ctx context.Context, route string, status int) {
	_m.Called(ctx, route, status)
}

// RecordRequestStart provides a mock function with given fields: ctx, route
func (_m *HTTPMetrics) RecordRequestStart(ctx context.Context, route string) {
	_m.Called(ctx, route)
}

// NewHTTPMetrics creates a new instance of HTTPMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPMetrics {
	mock := &HTTPMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
