// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/turtacn/cbc/internal/domain/models"
)

// KeyLifecycleRegistry is an autogenerated mock type for the KeyLifecycleRegistry type
type KeyLifecycleRegistry struct {
	mock.Mock
}

// LogEvent provides a mock function with given fields: ctx, event
func (_m *KeyLifecycleRegistry) LogEvent(ctx context.Context, event models.KLREvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for LogEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.KLREvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKeyLifecycleRegistry creates a new instance of KeyLifecycleRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyLifecycleRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyLifecycleRegistry {
	mock := &KeyLifecycleRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
