// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	rsa "crypto/rsa"
)

// KeyManagementService is an autogenerated mock type for the KeyManagementService type
type KeyManagementService struct {
	mock.Mock
}

// CompromiseKey provides a mock function with given fields: ctx, tenantID, kid, reason
func (_m *KeyManagementService) CompromiseKey(ctx context.Context, tenantID string, kid string, reason string) error {
	ret := _m.Called(ctx, tenantID, kid, reason)

	if len(ret) == 0 {
		panic("no return value specified for CompromiseKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tenantID, kid, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateJWT provides a mock function with given fields: ctx, tenantID, claims
func (_m *KeyManagementService) GenerateJWT(ctx context.Context, tenantID string, claims jwt.Claims) (string, string, error) {
	ret := _m.Called(ctx, tenantID, claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, jwt.Claims) (string, string, error)); ok {
		return rf(ctx, tenantID, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, jwt.Claims) string); ok {
		r0 = rf(ctx, tenantID, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, jwt.Claims) string); ok {
		r1 = rf(ctx, tenantID, claims)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, jwt.Claims) error); ok {
		r2 = rf(ctx, tenantID, claims)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTenantPublicKeys provides a mock function with given fields: ctx, tenantID
func (_m *KeyManagementService) GetTenantPublicKeys(ctx context.Context, tenantID string) (map[string]*rsa.PublicKey, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantPublicKeys")
	}

	var r0 map[string]*rsa.PublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]*rsa.PublicKey, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]*rsa.PublicKey); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*rsa.PublicKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateTenantKey provides a mock function with given fields: ctx, tenantID
func (_m *KeyManagementService) RotateTenantKey(ctx context.Context, tenantID string) (string, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for RotateTenantKey")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyJWT provides a mock function with given fields: ctx, tokenString, tenantID
func (_m *KeyManagementService) VerifyJWT(ctx context.Context, tokenString string, tenantID string) (jwt.MapClaims, error) {
	ret := _m.Called(ctx, tokenString, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyJWT")
	}

	var r0 jwt.MapClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (jwt.MapClaims, error)); ok {
		return rf(ctx, tokenString, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) jwt.MapClaims); ok {
		r0 = rf(ctx, tokenString, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tokenString, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKeyManagementService creates a new instance of KeyManagementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyManagementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyManagementService {
	mock := &KeyManagementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
