// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/turtacn/cbc/internal/domain/models"

	rsa "crypto/rsa"
)

// KeyProvider is an autogenerated mock type for the KeyProvider type
type KeyProvider struct {
	mock.Mock
}

// Backup provides a mock function with given fields: ctx, providerRef
func (_m *KeyProvider) Backup(ctx context.Context, providerRef string) ([]byte, error) {
	ret := _m.Called(ctx, providerRef)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, providerRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, providerRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, providerRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateKey provides a mock function with given fields: ctx, keySpec
func (_m *KeyProvider) GenerateKey(ctx context.Context, keySpec models.KeySpec) (string, string, *rsa.PublicKey, error) {
	ret := _m.Called(ctx, keySpec)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKey")
	}

	var r0 string
	var r1 string
	var r2 *rsa.PublicKey
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, models.KeySpec) (string, string, *rsa.PublicKey, error)); ok {
		return rf(ctx, keySpec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.KeySpec) string); ok {
		r0 = rf(ctx, keySpec)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.KeySpec) string); ok {
		r1 = rf(ctx, keySpec)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.KeySpec) *rsa.PublicKey); ok {
		r2 = rf(ctx, keySpec)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*rsa.PublicKey)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, models.KeySpec) error); ok {
		r3 = rf(ctx, keySpec)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetPublicKey provides a mock function with given fields: ctx, providerRef
func (_m *KeyProvider) GetPublicKey(ctx context.Context, providerRef string) (*rsa.PublicKey, error) {
	ret := _m.Called(ctx, providerRef)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 *rsa.PublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*rsa.PublicKey, error)); ok {
		return rf(ctx, providerRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *rsa.PublicKey); ok {
		r0 = rf(ctx, providerRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, providerRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, encryptedBlob
func (_m *KeyProvider) Restore(ctx context.Context, encryptedBlob []byte) (string, error) {
	ret := _m.Called(ctx, encryptedBlob)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return rf(ctx, encryptedBlob)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = rf(ctx, encryptedBlob)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, encryptedBlob)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Sign provides a mock function with given fields: ctx, providerRef, digest
func (_m *KeyProvider) Sign(ctx context.Context, providerRef string, digest []byte) ([]byte, error) {
	ret := _m.Called(ctx, providerRef, digest)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) ([]byte, error)); ok {
		return rf(ctx, providerRef, digest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) []byte); ok {
		r0 = rf(ctx, providerRef, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, providerRef, digest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKeyProvider creates a new instance of KeyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyProvider {
	mock := &KeyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
