// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	"time"

	"github.com/stretchr/testify/mock"
)

// Metrics is an autogenerated mock type for the Metrics type
type Metrics struct {
	mock.Mock
}

// RecordTokenIssue provides a mock function with given fields: tenantID, grantType, success, duration, errorCode
func (_m *Metrics) RecordTokenIssue(tenantID string, grantType string, success bool, duration time.Duration, errorCode string) {
	_m.Called(tenantID, grantType, success, duration, errorCode)
}

// RecordTokenIssueByTrust provides a mock function with given fields: trustLevel, tenantID
func (_m *Metrics) RecordTokenIssueByTrust(trustLevel string, tenantID string) {
	_m.Called(trustLevel, tenantID)
}

// RecordTokenVerify provides a mock function with given fields: tenantID, success, errorCode
func (_m *Metrics) RecordTokenVerify(tenantID string, success bool, errorCode string) {
	_m.Called(tenantID, success, errorCode)
}

// RecordTokenRevoke provides a mock function with given fields: tenantID, reason
func (_m *Metrics) RecordTokenRevoke(tenantID string, reason string) {
	_m.Called(tenantID, reason)
}

// RecordDeviceRegister provides a mock function with given fields: tenantID, success, errorCode
func (_m *Metrics) RecordDeviceRegister(tenantID string, success bool, errorCode string) {
	_m.Called(tenantID, success, errorCode)
}

// RecordRateLimitHit provides a mock function with given fields: tenantID, scope
func (_m *Metrics) RecordRateLimitHit(tenantID string, scope string) {
	_m.Called(tenantID, scope)
}

// RecordCacheAccess provides a mock function with given fields: cacheType, hit
func (_m *Metrics) RecordCacheAccess(cacheType string, hit bool) {
	_m.Called(cacheType, hit)
}

// RecordDBQuery provides a mock function with given fields: operation, duration
func (_m *Metrics) RecordDBQuery(operation string, duration time.Duration) {
	_m.Called(operation, duration)
}

// UpdateDBConnections provides a mock function with given fields: active, idle
func (_m *Metrics) UpdateDBConnections(active int, idle int) {
	_m.Called(active, idle)
}

// RecordVaultAPI provides a mock function with given fields: operation, duration, err
func (_m *Metrics) RecordVaultAPI(operation string, duration time.Duration, err error) {
	_m.Called(operation, duration, err)
}

// UpdateGoroutineCount provides a mock function with given fields: count
func (_m *Metrics) UpdateGoroutineCount(count int) {
	_m.Called(count)
}

type mockConstructorTestingTNewMetrics interface {
	mock.TestingT
	Cleanup(func())
}

// NewMetrics creates a new instance of Metrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMetrics(t mockConstructorTestingTNewMetrics) *Metrics {
	mock := &Metrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
