// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/turtacn/cbc/internal/domain/models"
)

// PolicyEngine is an autogenerated mock type for the PolicyEngine type
type PolicyEngine struct {
	mock.Mock
}

// CheckKeyGeneration provides a mock function with given fields: ctx, policy
func (_m *PolicyEngine) CheckKeyGeneration(ctx context.Context, policy models.PolicyRequest) error {
	ret := _m.Called(ctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for CheckKeyGeneration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.PolicyRequest) error); ok {
		r0 = rf(ctx, policy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EvaluateTrustLevel provides a mock function with given fields: ctx, riskProfile
func (_m *PolicyEngine) EvaluateTrustLevel(ctx context.Context, riskProfile *models.TenantRiskProfile) models.TrustLevel {
	ret := _m.Called(ctx, riskProfile)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateTrustLevel")
	}

	var r0 models.TrustLevel
	if rf, ok := ret.Get(0).(func(context.Context, *models.TenantRiskProfile) models.TrustLevel); ok {
		r0 = rf(ctx, riskProfile)
	} else {
		r0 = ret.Get(0).(models.TrustLevel)
	}

	return r0
}

// NewPolicyEngine creates a new instance of PolicyEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyEngine {
	mock := &PolicyEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
