// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/turtacn/cbc/internal/domain/service"

	time "time"
)

// RateLimitService is an autogenerated mock type for the RateLimitService type
type RateLimitService struct {
	mock.Mock
}

// Allow provides a mock function with given fields: ctx, dimension, key, identifier
func (_m *RateLimitService) Allow(ctx context.Context, dimension service.RateLimitDimension, key string, identifier string) (bool, int, time.Time, error) {
	ret := _m.Called(ctx, dimension, key, identifier)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	var r1 int
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, service.RateLimitDimension, string, string) (bool, int, time.Time, error)); ok {
		return rf(ctx, dimension, key, identifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.RateLimitDimension, string, string) bool); ok {
		r0 = rf(ctx, dimension, key, identifier)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.RateLimitDimension, string, string) int); ok {
		r1 = rf(ctx, dimension, key, identifier)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, service.RateLimitDimension, string, string) time.Time); ok {
		r2 = rf(ctx, dimension, key, identifier)
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func(context.Context, service.RateLimitDimension, string, string) error); ok {
		r3 = rf(ctx, dimension, key, identifier)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewRateLimitService creates a new instance of RateLimitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimitService {
	mock := &RateLimitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
