// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/turtacn/cbc/internal/domain/models"
)

// RiskOracle is an autogenerated mock type for the RiskOracle type
type RiskOracle struct {
	mock.Mock
}

// GetTenantRisk provides a mock function with given fields: ctx, tenantID, agentID
func (_m *RiskOracle) GetTenantRisk(ctx context.Context, tenantID string, agentID string) (*models.TenantRiskProfile, error) {
	ret := _m.Called(ctx, tenantID, agentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantRisk")
	}

	var r0 *models.TenantRiskProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.TenantRiskProfile, error)); ok {
		return rf(ctx, tenantID, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.TenantRiskProfile); ok {
		r0 = rf(ctx, tenantID, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TenantRiskProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRiskOracle creates a new instance of RiskOracle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskOracle(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskOracle {
	mock := &RiskOracle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
