// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenBlacklistStore is an autogenerated mock type for the TokenBlacklistStore type
type TokenBlacklistStore struct {
	mock.Mock
}

// IsRevoked provides a mock function with given fields: ctx, tenantID, jti
func (_m *TokenBlacklistStore) IsRevoked(ctx context.Context, tenantID string, jti string) (bool, error) {
	ret := _m.Called(ctx, tenantID, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, tenantID, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, tenantID, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Revoke provides a mock function with given fields: ctx, tenantID, jti, exp
func (_m *TokenBlacklistStore) Revoke(ctx context.Context, tenantID string, jti string, exp time.Time) error {
	ret := _m.Called(ctx, tenantID, jti, exp)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, tenantID, jti, exp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenBlacklistStore creates a new instance of TokenBlacklistStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenBlacklistStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenBlacklistStore {
	mock := &TokenBlacklistStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
