// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	constants "github.com/turtacn/cbc/pkg/constants"

	mock "github.com/stretchr/testify/mock"

	models "github.com/turtacn/cbc/internal/domain/models"

	time "time"
)

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

// CleanupExpiredTokens provides a mock function with given fields: ctx, before
func (_m *TokenService) CleanupExpiredTokens(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpiredTokens")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateAccessToken provides a mock function with given fields: ctx, refreshToken, requestedScope
func (_m *TokenService) GenerateAccessToken(ctx context.Context, refreshToken *models.Token, requestedScope []string) (*models.Token, error) {
	ret := _m.Called(ctx, refreshToken, requestedScope)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 *models.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Token, []string) (*models.Token, error)); ok {
		return rf(ctx, refreshToken, requestedScope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Token, []string) *models.Token); ok {
		r0 = rf(ctx, refreshToken, requestedScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Token, []string) error); ok {
		r1 = rf(ctx, refreshToken, requestedScope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IntrospectToken provides a mock function with given fields: ctx, tokenString, tokenTypeHint
func (_m *TokenService) IntrospectToken(ctx context.Context, tokenString string, tokenTypeHint string) (*models.TokenIntrospection, error) {
	ret := _m.Called(ctx, tokenString, tokenTypeHint)

	if len(ret) == 0 {
		panic("no return value specified for IntrospectToken")
	}

	var r0 *models.TokenIntrospection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.TokenIntrospection, error)); ok {
		return rf(ctx, tokenString, tokenTypeHint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.TokenIntrospection); ok {
		r0 = rf(ctx, tokenString, tokenTypeHint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenIntrospection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tokenString, tokenTypeHint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsTokenRevoked provides a mock function with given fields: ctx, jti
func (_m *TokenService) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IssueToken provides a mock function with given fields: ctx, tenantID, subject, scope
func (_m *TokenService) IssueToken(ctx context.Context, tenantID string, subject string, scope []string) (*models.Token, error) {
	ret := _m.Called(ctx, tenantID, subject, scope)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 *models.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) (*models.Token, error)); ok {
		return rf(ctx, tenantID, subject, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) *models.Token); ok {
		r0 = rf(ctx, tenantID, subject, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = rf(ctx, tenantID, subject, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IssueTokenPair provides a mock function with given fields: ctx, tenantID, agentID, deviceFingerprint, scope, metadata
func (_m *TokenService) IssueTokenPair(ctx context.Context, tenantID string, agentID string, deviceFingerprint string, scope []string, metadata map[string]interface{}) (*models.Token, *models.Token, error) {
	ret := _m.Called(ctx, tenantID, agentID, deviceFingerprint, scope, metadata)

	if len(ret) == 0 {
		panic("no return value specified for IssueTokenPair")
	}

	var r0 *models.Token
	var r1 *models.Token
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string, map[string]interface{}) (*models.Token, *models.Token, error)); ok {
		return rf(ctx, tenantID, agentID, deviceFingerprint, scope, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string, map[string]interface{}) *models.Token); ok {
		r0 = rf(ctx, tenantID, agentID, deviceFingerprint, scope, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []string, map[string]interface{}) *models.Token); ok {
		r1 = rf(ctx, tenantID, agentID, deviceFingerprint, scope, metadata)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Token)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, []string, map[string]interface{}) error); ok {
		r2 = rf(ctx, tenantID, agentID, deviceFingerprint, scope, metadata)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RefreshToken provides a mock function with given fields: ctx, refreshTokenString, requestedScope
func (_m *TokenService) RefreshToken(ctx context.Context, refreshTokenString string, requestedScope []string) (*models.Token, *models.Token, error) {
	ret := _m.Called(ctx, refreshTokenString, requestedScope)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *models.Token
	var r1 *models.Token
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (*models.Token, *models.Token, error)); ok {
		return rf(ctx, refreshTokenString, requestedScope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) *models.Token); ok {
		r0 = rf(ctx, refreshTokenString, requestedScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) *models.Token); ok {
		r1 = rf(ctx, refreshTokenString, requestedScope)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Token)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []string) error); ok {
		r2 = rf(ctx, refreshTokenString, requestedScope)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RevokeToken provides a mock function with given fields: ctx, jti, tenantID, reason
func (_m *TokenService) RevokeToken(ctx context.Context, jti string, tenantID string, reason string) error {
	ret := _m.Called(ctx, jti, tenantID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, jti, tenantID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateTokenClaims provides a mock function with given fields: ctx, token, validationContext
func (_m *TokenService) ValidateTokenClaims(ctx context.Context, token *models.Token, validationContext map[string]interface{}) (bool, error) {
	ret := _m.Called(ctx, token, validationContext)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTokenClaims")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Token, map[string]interface{}) (bool, error)); ok {
		return rf(ctx, token, validationContext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Token, map[string]interface{}) bool); ok {
		r0 = rf(ctx, token, validationContext)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Token, map[string]interface{}) error); ok {
		r1 = rf(ctx, token, validationContext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyToken provides a mock function with given fields: ctx, tokenString, tokenType, tenantID
func (_m *TokenService) VerifyToken(ctx context.Context, tokenString string, tokenType constants.TokenType, tenantID string) (*models.Token, error) {
	ret := _m.Called(ctx, tokenString, tokenType, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *models.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, constants.TokenType, string) (*models.Token, error)); ok {
		return rf(ctx, tokenString, tokenType, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, constants.TokenType, string) *models.Token); ok {
		r0 = rf(ctx, tokenString, tokenType, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, constants.TokenType, string) error); ok {
		r1 = rf(ctx, tokenString, tokenType, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
