// Code generated by mockery v2.14.0. DO NOT EDIT.

package redis

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/turtacn/cbc/internal/domain/models"
)

// MockAuditService is an autogenerated mock type for the AuditService type
type MockAuditService struct {
	mock.Mock
}

// LogEvent provides a mock function with given fields: ctx, event
func (_m *MockAuditService) LogEvent(ctx context.Context, event models.AuditEvent) error {
	ret := _m.Called(ctx, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AuditEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockAuditService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAuditService creates a new instance of MockAuditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAuditService(t mockConstructorTestingTNewMockAuditService) *MockAuditService {
	mock := &MockAuditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
