// Code generated by Jules AI Test Generator. DO NOT EDIT.
package redis

import (
	"context"
	"testing"
	"time"

	"github.com/alicebob/miniredis/v2"
	"github.com/redis/go-redis/v9"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	"github.com/turtacn/cbc/internal/domain/models"
	"github.com/turtacn/cbc/pkg/logger"
)

func TestTokenBlacklist(t *testing.T) {
	mr, err := miniredis.Run()
	require.NoError(t, err, "Failed to start miniredis")
	defer mr.Close()

	rdb := redis.NewClient(&redis.Options{
		Addr: mr.Addr(),
	})

	mockAudit := new(MockAuditService)
	noopLogger := logger.NewNoopLogger()

	store := NewTokenBlacklistStore(rdb, mockAudit, noopLogger)
	ctx := context.Background()

	tenantID := "tenant-1"
	jti := "jti-1"

	t.Run("IsRevoked_NotRevoked", func(t *testing.T) {
		revoked, err := store.IsRevoked(ctx, tenantID, jti)
		assert.NoError(t, err)
		assert.False(t, revoked)
	})

	t.Run("RevokeAndCheck_PublishesToKafka", func(t *testing.T) {
		exp := time.Now().Add(10 * time.Minute)

		// Expect a call to the audit service
		mockAudit.On("LogEvent", ctx, mock.MatchedBy(func(event models.AuditEvent) bool {
			return event.Action == "token_revoked_globally" &&
				event.TenantID == tenantID &&
				event.Metadata["jti"] == jti
		})).Return(nil).Once()

		err := store.Revoke(ctx, tenantID, jti, exp)
		assert.NoError(t, err)

		revoked, err := store.IsRevoked(ctx, tenantID, jti)
		assert.NoError(t, err)
		assert.True(t, revoked)

		// Assert that the mock expectation was met
		mockAudit.AssertExpectations(t)
	})

	t.Run("Revoke_Expired_DoesNotPublish", func(t *testing.T) {
		jtiExpired := "jti-expired"
		exp := time.Now().Add(-10 * time.Minute)
		err := store.Revoke(ctx, tenantID, jtiExpired, exp)
		assert.NoError(t, err)

		revoked, err := store.IsRevoked(ctx, tenantID, jtiExpired)
		assert.NoError(t, err)
		assert.False(t, revoked)
	})

	t.Run("CheckTTL", func(t *testing.T) {
		jtiTTL := "jti-ttl"
		exp := time.Now().Add(5 * time.Second)

		// Expect a call to the audit service
		mockAudit.On("LogEvent", ctx, mock.MatchedBy(func(event models.AuditEvent) bool {
			return event.Action == "token_revoked_globally" &&
				event.TenantID == tenantID &&
				event.Metadata["jti"] == jtiTTL
		})).Return(nil).Once()

		err := store.Revoke(ctx, tenantID, jtiTTL, exp)
		assert.NoError(t, err)

		revoked, err := store.IsRevoked(ctx, tenantID, jtiTTL)
		assert.NoError(t, err)
		assert.True(t, revoked)

		// Advance time
		mr.FastForward(6 * time.Second)

		revoked, err = store.IsRevoked(ctx, tenantID, jtiTTL)
		assert.NoError(t, err)
		assert.False(t, revoked, "Token should not be revoked after TTL expires")
	})
}
