// Code generated by Jules AI Test Generator. DO NOT EDIT.
package unit

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/turtacn/cbc/internal/application/dto"
	grpc_interface "github.com/turtacn/cbc/internal/interfaces/grpc"
	authpb "github.com/turtacn/cbc/internal/interfaces/grpc/proto"
	"github.com/turtacn/cbc/pkg/errors"
	"github.com/turtacn/cbc/pkg/logger"
)

type MockAuthAppService struct {
	mock.Mock
}

func (m *MockAuthAppService) IssueToken(ctx context.Context, req *dto.IssueTokenRequest) (*dto.TokenResponse, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TokenResponse), args.Error(1)
}

func (m *MockAuthAppService) RefreshToken(ctx context.Context, req *dto.RefreshTokenRequest) (*dto.TokenResponse, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TokenResponse), args.Error(1)
}

func (m *MockAuthAppService) RevokeToken(ctx context.Context, req *dto.RevokeTokenRequest) error {
	args := m.Called(ctx, req)
	return args.Error(0)
}

func (m *MockAuthAppService) IntrospectToken(ctx context.Context, token string) (*dto.TokenIntrospectionResponse, error) {
	args := m.Called(ctx, token)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TokenIntrospectionResponse), args.Error(1)
}

func (m *MockAuthAppService) RegisterDevice(ctx context.Context, req *dto.RegisterDeviceRequest) (*dto.TokenResponse, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TokenResponse), args.Error(1)
}

func TestAuthGRPCService_RevokeToken(t *testing.T) {
	testLogger := logger.NewDefaultLogger()
	ctx := context.Background()
	req := &authpb.RevokeTokenRequest{
		Token:  "some-token",
		Reason: "user logout",
	}

	t.Run("successful revocation", func(t *testing.T) {
		mockAuthApp := new(MockAuthAppService)
		grpcService := grpc_interface.NewAuthGRPCService(mockAuthApp, testLogger)

		expectedDTO := &dto.RevokeTokenRequest{
			Token:  req.Token,
			Reason: req.Reason,
		}
		mockAuthApp.On("RevokeToken", ctx, expectedDTO).Return(nil).Once()

		resp, err := grpcService.RevokeToken(ctx, req)
		assert.NoError(t, err)
		assert.NotNil(t, resp)
		assert.True(t, resp.Revoked)

		mockAuthApp.AssertExpectations(t)
	})

	t.Run("app service returns an error", func(t *testing.T) {
		mockAuthApp := new(MockAuthAppService)
		grpcService := grpc_interface.NewAuthGRPCService(mockAuthApp, testLogger)

		expectedDTO := &dto.RevokeTokenRequest{
			Token:  req.Token,
			Reason: req.Reason,
		}
		mockAuthApp.On("RevokeToken", ctx, expectedDTO).Return(errors.ErrInvalidRequest("invalid token")).Once()

		resp, err := grpcService.RevokeToken(ctx, req)
		assert.Error(t, err)
		assert.Nil(t, resp)

		mockAuthApp.AssertExpectations(t)
	})
}
