// Code generated by Jules AI Test Generator. DO NOT EDIT.
package unit

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/turtacn/cbc/internal/application/dto"
	"github.com/turtacn/cbc/internal/interfaces/http/handlers"
	"github.com/turtacn/cbc/pkg/errors"
	"github.com/turtacn/cbc/pkg/logger"
	"github.com/turtacn/cbc/tests/mocks"
)

func TestAuthHandler_RefreshToken(t *testing.T) {
	gin.SetMode(gin.TestMode)
	log := logger.NewNoopLogger()
	metrics := new(mocks.MockHTTPMetrics)
	metrics.On("RecordRequestStart", mock.Anything, mock.Anything).Return()
	metrics.On("RecordRequestDuration", mock.Anything, mock.Anything, mock.Anything, mock.AnythingOfType("time.Duration")).Return()
	metrics.On("RecordRequestError", mock.Anything, mock.Anything, mock.Anything).Return()

	t.Run("success", func(t *testing.T) {
		mockAuthApp := new(mocks.MockAuthAppService)
		authHandler := handlers.NewAuthHandler(mockAuthApp, metrics, log)

		w := httptest.NewRecorder()
		c, _ := gin.CreateTestContext(w)

		reqBody := dto.TokenRefreshRequest{RefreshToken: "valid-refresh-token"}
		jsonBody, _ := json.Marshal(reqBody)
		req, _ := http.NewRequest(http.MethodPost, "/api/v1/auth/refresh", bytes.NewBuffer(jsonBody))
		c.Request = req

		expectedResp := &dto.TokenResponse{AccessToken: "new-access-token"}
		mockAuthApp.On("RefreshToken", mock.Anything, mock.AnythingOfType("*dto.TokenRefreshRequest")).Return(expectedResp, nil)

		authHandler.RefreshToken(c)

		assert.Equal(t, http.StatusOK, w.Code)
		var resp dto.TokenResponse
		json.Unmarshal(w.Body.Bytes(), &resp)
		assert.Equal(t, expectedResp.AccessToken, resp.AccessToken)
	})

	t.Run("invalid request", func(t *testing.T) {
		mockAuthApp := new(mocks.MockAuthAppService)
		authHandler := handlers.NewAuthHandler(mockAuthApp, metrics, log)

		w := httptest.NewRecorder()
		c, _ := gin.CreateTestContext(w)

		req, _ := http.NewRequest(http.MethodPost, "/api/v1/auth/refresh", bytes.NewBufferString("{"))
		c.Request = req

		authHandler.RefreshToken(c)

		assert.Equal(t, http.StatusBadRequest, w.Code)
	})
}

func TestAuthHandler_RevokeToken(t *testing.T) {
	gin.SetMode(gin.TestMode)
	log := logger.NewNoopLogger()
	metrics := new(mocks.MockHTTPMetrics)
	metrics.On("RecordRequestStart", mock.Anything, mock.Anything).Return()
	metrics.On("RecordRequestDuration", mock.Anything, mock.Anything, mock.Anything, mock.AnythingOfType("time.Duration")).Return()
	metrics.On("RecordRequestError", mock.Anything, mock.Anything, mock.Anything).Return()

	t.Run("success", func(t *testing.T) {
		mockAuthApp := new(mocks.MockAuthAppService)
		authHandler := handlers.NewAuthHandler(mockAuthApp, metrics, log)

		w := httptest.NewRecorder()
		c, _ := gin.CreateTestContext(w)

		reqBody := dto.TokenRevokeRequest{Token: "valid-token"}
		jsonBody, _ := json.Marshal(reqBody)
		req, _ := http.NewRequest(http.MethodPost, "/api/v1/auth/revoke", bytes.NewBuffer(jsonBody))
		c.Request = req

		mockAuthApp.On("RevokeToken", mock.Anything, mock.AnythingOfType("*dto.TokenRevokeRequest")).Return(nil)

		authHandler.RevokeToken(c)

		assert.Equal(t, http.StatusNoContent, w.Code)
	})

	t.Run("service error", func(t *testing.T) {
		mockAuthApp := new(mocks.MockAuthAppService)
		authHandler := handlers.NewAuthHandler(mockAuthApp, metrics, log)

		w := httptest.NewRecorder()
		c, _ := gin.CreateTestContext(w)

		reqBody := dto.TokenRevokeRequest{Token: "valid-token"}
		jsonBody, _ := json.Marshal(reqBody)
		req, _ := http.NewRequest(http.MethodPost, "/api/v1/auth/revoke", bytes.NewBuffer(jsonBody))
		c.Request = req

		mockAuthApp.On("RevokeToken", mock.Anything, mock.AnythingOfType("*dto.TokenRevokeRequest")).Return(errors.ErrServerError("internal error"))

		authHandler.RevokeToken(c)

		assert.Equal(t, http.StatusInternalServerError, w.Code)
	})
}
