// Code generated by Jules AI Test Generator. DO NOT EDIT.
package unit

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/turtacn/cbc/internal/application/dto"
	"github.com/turtacn/cbc/internal/interfaces/http/handlers"
	"github.com/turtacn/cbc/pkg/errors"
	"github.com/turtacn/cbc/pkg/logger"
	"github.com/turtacn/cbc/internal/domain/service/mocks"
)

func TestDeviceHandler_GetDevice(t *testing.T) {
	gin.SetMode(gin.TestMode)
	log := logger.NewNoopLogger()
	metrics := new(mocks.MockHTTPMetrics)
	metrics.On("RecordRequestStart", mock.Anything, mock.Anything).Return()
	metrics.On("RecordRequestDuration", mock.Anything, mock.Anything, mock.Anything, mock.AnythingOfType("time.Duration")).Return()
	metrics.On("RecordRequestError", mock.Anything, mock.Anything, mock.Anything).Return()

	t.Run("success", func(t *testing.T) {
		mockDeviceApp := new(mocks.MockDeviceAppService)
		deviceHandler := handlers.NewDeviceHandler(mockDeviceApp, metrics, log)

		w := httptest.NewRecorder()
		c, _ := gin.CreateTestContext(w)
		c.Params = gin.Params{gin.Param{Key: "device_id", Value: "dev-1"}}
		req, _ := http.NewRequest(http.MethodGet, "/api/v1/devices/dev-1", nil)
		c.Request = req

		expectedResp := &dto.DeviceResponse{DeviceID: "dev-1"}
		mockDeviceApp.On("GetDeviceInfo", mock.Anything, "dev-1").Return(expectedResp, nil)

		deviceHandler.GetDevice(c)

		assert.Equal(t, http.StatusOK, w.Code)
		var resp dto.DeviceResponse
		json.Unmarshal(w.Body.Bytes(), &resp)
		assert.Equal(t, expectedResp.DeviceID, resp.DeviceID)
	})

	t.Run("not found", func(t *testing.T) {
		mockDeviceApp := new(mocks.MockDeviceAppService)
		deviceHandler := handlers.NewDeviceHandler(mockDeviceApp, metrics, log)

		w := httptest.NewRecorder()
		c, _ := gin.CreateTestContext(w)
		c.Params = gin.Params{gin.Param{Key: "device_id", Value: "dev-not-found"}}
		req, _ := http.NewRequest(http.MethodGet, "/api/v1/devices/dev-not-found", nil)
		c.Request = req

		mockDeviceApp.On("GetDeviceInfo", mock.Anything, "dev-not-found").Return(nil, errors.ErrDeviceNotFound("dev-not-found"))

		deviceHandler.GetDevice(c)

		assert.Equal(t, http.StatusNotFound, w.Code)
	})
}

func TestDeviceHandler_UpdateDevice(t *testing.T) {
	gin.SetMode(gin.TestMode)
	log := logger.NewNoopLogger()
	metrics := new(mocks.MockHTTPMetrics)
	metrics.On("RecordRequestStart", mock.Anything, mock.Anything).Return()
	metrics.On("RecordRequestDuration", mock.Anything, mock.Anything, mock.Anything, mock.AnythingOfType("time.Duration")).Return()
	metrics.On("RecordRequestError", mock.Anything, mock.Anything, mock.Anything).Return()

	t.Run("success", func(t *testing.T) {
		mockDeviceApp := new(mocks.MockDeviceAppService)
		deviceHandler := handlers.NewDeviceHandler(mockDeviceApp, metrics, log)

		w := httptest.NewRecorder()
		c, _ := gin.CreateTestContext(w)
		c.Params = gin.Params{gin.Param{Key: "device_id", Value: "dev-1"}}

		reqBody := dto.DeviceUpdateRequest{Status: "active"}
		jsonBody, _ := json.Marshal(reqBody)
		req, _ := http.NewRequest(http.MethodPut, "/api/v1/devices/dev-1", bytes.NewBuffer(jsonBody))
		c.Request = req

		mockDeviceApp.On("UpdateDeviceInfo", mock.Anything, "dev-1", mock.AnythingOfType("*dto.DeviceUpdateRequest")).Return(&dto.DeviceResponse{}, nil)

		deviceHandler.UpdateDevice(c)

		assert.Equal(t, http.StatusNoContent, w.Code)
	})

	t.Run("invalid request", func(t *testing.T) {
		mockDeviceApp := new(mocks.MockDeviceAppService)
		deviceHandler := handlers.NewDeviceHandler(mockDeviceApp, metrics, log)

		w := httptest.NewRecorder()
		c, _ := gin.CreateTestContext(w)
		c.Params = gin.Params{gin.Param{Key: "device_id", Value: "dev-1"}}
		req, _ := http.NewRequest(http.MethodPut, "/api/v1/devices/dev-1", bytes.NewBufferString("{"))
		c.Request = req

		deviceHandler.UpdateDevice(c)

		assert.Equal(t, http.StatusBadRequest, w.Code)
	})
}
